@Echo off
Echo I gonna copy all Chemical's doco files to printer.
Echo Now, hit Ctrl/Break if you better back or
Pause
Echo Printing MATBASC.TXT - the math basics of Chemical
Copy MATHBASC.TXT Prn >Nul
Echo Printing HELPME!.TXT - the short conversation between you and authors
Copy HELPME!.TXT Prn >Nul 
Echo Printing SCHEME.TXT  - the scheme showing where and how you can go 
Copy SCHEME.TXT Prn >Nul 
Echo Printing SAMPLE.TXT  - read it and do things you read while reading
Copy SAMPLE.TXT Prn >Nul 
